### ISSUE TITLE
Ensure the function expansion result does not refer to missing sub-rules or functions.

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/grammar_parser#11]
See https://github.com/tue-robotics/grammar_parser/pull/10/files#diff-387376fd41ca31b546f35d9565e348c1R408

**Comment by alberth** [comment]
A function is random code that produces the name of the next rule to apply. This code is being executed while processing a sentence. The set of available rules is decided in the grammar file, much much earlier.

You cannot investigate the code and decide what names it could produce. At best you can define the set allowed names that the function can produce in advance. You could check that set against the names of the available rules.

Even when that is all in place, you're still at the mercy of the function result. If the function produces something else at run time than it promised you're still dead. The main difference is that you can flag the function as being faulty rather than failing to find some unknown rule-name while processing the function-terminal. I considered that difference so small that it's not worth fixing.

**Comment by LoyVanBeek** [comment]
I've never seen an issue with it either, because we don't use it very often AFAIK.
